package ink.utils;

/**
 * Created by USER on 2016-06-19.
 */
public class Constants {
    public static final String MAIN_URL = "http://104.196.103.60/Ink_Base_project_1992_no_15_dp_deployed_57_olAllolclslf_8954/";
    public static final String USER_IMAGES_FOLDER = "UserImages/";
    public static final String GROUP_IMAGES_FOLDER = "GroupImages/";
    public static final String ANIMATED_STICKERS_FOLDER = "AnimatedStickers/";
    public static final String ADD_GROUP_URL = "AddGroup.php";
    public static final String GROUP_REQUESTS_URL = "GetGroupRequests.php";
    public static final String USER_GIFS_URL = "GetUserGifs.php";
    public static final String DELETE_ACCOUNT_URL = "DeleteAccount.php";
    public static final String SEARCH_GROUP_URL = "SearchGroups.php";
    public static final String SEND_CHAT_ROULETTE_MESSAGE = "SendChatRouletteMessage.php";
    public static final String GET_USER_STATUS = "GetUserStatus.php";
    public static final String DISCONNECT_URL = "Disconnect.php";
    public static final String USER_COINS_URL = "GetUserCoins.php";
    public static final String SHOP_COINS_URL = "GetCoinsShop.php";
    public static final String PING_TIME_URL = "PingTime.php";
    public static final String SHOP_PACKS_URL = "GetPacks.php";
    public static final String JOIN_GROUP_URL = "JoinGroup.php";
    public static final String ADD_GROUP_MESSAGE_URL = "AddGroupMessage.php";
    public static final String GET_GROUP_URL = "GetGroups.php";
    public static final String REGISTER_URL = "Register.php";
    public static final String MY_GROUPS_URL = "UserGroups.php";
    public static final String SEARCH_PERSON_URL = "SearchPerson.php";
    public static final String GROUP_PARTICIPANTS_URL = "GroupParticipants.php";
    public static final String GROUP_MESSAGES_URL = "GroupMessages.php";
    public static final String NOTIFY_OPPONENT = "NotifyOpponent.php";
    public static final String RESPOND_TO_REQUEST_URL = "RespondToRequest.php";
    public static final String LOGIN_URL = "Login.php";
    public static final String FRIENDS_URL = "UserFriends.php";
    public static final String SINGLE_USER_URL = "SingleUser.php";
    public static final String MESSAGES_URL = "Messages.php";
    public static final String UPLOADED_FILES_DIR = "UserUploads/";
    public static final String SEND_MESSAGE_URL = "SendMessage.php";
    public static final String GENDER_MALE = "Male";
    public static final String GENDER_FEMALE = "Female";
    public static final String STATUS_DELIVERED = "delivered";
    public static final String STATUS_NOT_DELIVERED = "not sent";
    public static final String SINGLE_USER_MESSAGES = "SingleUserMessages.php";
    public static final String CHAT_MESSAGES = "ChatMessages.php";
    public static final String REGISTER_TOKEN = "RegisterToken.php";
    public static final String REQUEST_DELETE_URL = "RequestDeleteMessage.php";
    public static final String GET_POSTS_URL = "GetPosts.php";
    public static final String UPDATE_DETAILS = "UpdateDetails.php";
    public static final String MAKE_POST_URL = "MakePost.php";
    public static final String LIKE_URL = "LikePost.php";
    public static final String GET_COMMENTS_URL = "GetComments.php";
    public static final String SOCIAL_LOGIN_URL = "SocialLogin.php";
    public static final String ADD_COMMENT_URL = "AddComment.php";
    public static final int TEXT_VIEW_DEFAULT_COLOR = android.R.color.tab_indicator_text;
    public static final String TYPE_MESSAGE = "message";
    public static final String TYPE_REQUEST = "request";
    public static final String TYPE_CHAT_ROULETTE = "chatRoulette";
    public static final String WAITERS_QUE = "WaitRoomQue.php";
    public static final String GET_WAITERS = "GetWaitersQue.php";
    public static final String TYPE_ACCEPT_REQUEST = "0";
    public static final String TYPE_DENY_REQUEST = "1";
    public static final String STATUS_WAITING_NOT_AVAILABLE = "waiting_not_available";
    public static final String STATUS_AVAILABLE = "available";
    public static final String STATUS_IN_CHAT = "inChat";
    public static final String ACTION_UPDATE = "update";
    public static final String ACTION_DELETE = "delete";
    public static final String ACTION_INSERT = "insert";
    public static final String ANDROID_RESOURCE_DIR = "android.resource://";
    public static final String HUAWEI_MODEL = "HUAWEI";
    public static final String SERVER_TIME_ZONE = "America/Los_Angeles";
    public static final String CLOUD_CLIENT_ID = "15bf6f497229585b1cf45983d3d65b10";
    public static final String CLOUD_API_URL = "https://api.soundcloud.com";
    public static final String TYPE_CALL = "type=call";
    public static final String SUBJECT_FEEDBACK = "Feedback";
    public static final String SUBJECT_REQUEST_SUPPORT = "Support Needed";
    public static final String FEEDBACK_EMAIL = "support@vaentertaiment.xyz";
    public static final String CONTACT_EMAIL = "contact@vaentertaiment.xyz";
    public static final String SOCIAL_TYPE_FACEBOOK = "facebook";
    public static final String SOCIAL_TYPE_GOOGLE = "google";
    public static final String SERVER_AUTH_KEY = "fsahga-s447489asg-gGgashagasgfag-JKGKAJGKAS-gasgasga678sag8as-GASGJASKLG";
    public static final String NO_IMAGE_NAME = "no_image.png";
    public static final String NO_IMAGE_URL = MAIN_URL + USER_IMAGES_FOLDER + NO_IMAGE_NAME;
    public static final String ANDROID_DRAWABLE_DIR = ANDROID_RESOURCE_DIR + "com.ink" + "/drawable/";
    public static final String DELETE_POST_URL = "DeletePost.php";
}

